---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest
      tags: update

    - name: Install Docker
      yum:
        name:
          - docker
        state: present
      tags: install

    - name: Install Docker Compose (official)
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      tags: install

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      tags: service

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      tags: user

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Debug Docker version
      debug:
        var: docker_version.stdout

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Debug Docker Compose version
      debug:
        var: docker_compose_version.stdout