name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files to check for index.html
        run: ls -al sample-app/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check buildx builder
        run: docker buildx ls

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t albinfrancis12/my-app:latest -f ./sample-app/Dockerfile ./sample-app --push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to EC2 instance via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker images  # Debugging: List all images
            docker pull albinfrancis12/my-app1:latest
            docker images  # Debugging: Verify the image was pulled
            docker stop my-container || true
            docker rm my-container || true
            docker run -d --name my-container -p 80:80 albinfrancis12/my-app1:latest